### PR TITLE
Call convert_value on underlying expression if available

### PR DESCRIPTION
**Pull request by hottwaj**
This is a fix for #26 

Needs a unit test added

### CODE REVIEW

**Comment by schinckel** [comment]
Yeah, I'd love to see (a) the code that needs this, and (b) a unit test.

I'm not sure I'm doing anything (or ever have done) with this method, so I'm more than happy to make changes.

**Comment by hottwaj** [comment]
Thanks, I've added unit tests that covers some examples:
- using Trunc would fail on postgres without this change
- a slightly more contrived example (ValuesMap) would fail on all databases without this change

**Comment by hottwaj** [comment]
@schinckel I think with the unittest I've added it should be clearer what's going on here now - would you be able to take a look when time allows?  Thanks!

**Comment by schinckel** [comment]
Oh yeah, that's really nice. I can see a bunch of places where I'll be able to use that to replace some Case/When expressions.

Will this work with an Enum? (I think it will, just haven't had a chance to try it out yet).

**Review by schinckel — APPROVED** [review]

**Comment by hottwaj** [comment]
Great thanks!  I think you can return whatever data you like in the convert stage (as long as your function is the last converter or provides data compatible with any subsequent converters), so yes I expect you can return Enums if desired :)

**Pull request merged**
